-- Server-side thumbnails for media. New image/GIF uploads get a 240px webp
-- thumbnail generated by Sharp at upload time and stored alongside the
-- original under media/uploads/thumbnails/. Pre-existing rows stay NULL
-- until backfilled via POST /api/media/backfill-thumbnails or re-uploaded;
-- the frontend falls back to the original storage_url in that case.

ALTER TABLE media ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
